-- Affiliates core schema for tracking referrals, clicks, and earnings

-- Affiliates (one per user who joins the program)
create table if not exists public.affiliates (
  affiliate_id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  username text generated always as (split_part(coalesce(lower(email), ''), '@', 1)) stored,
  email text not null,
  payment_info text,
  created_at timestamptz not null default now(),
  unique(user_id)
);

-- Affiliate codes (multiple codes per affiliate if needed)
create table if not exists public.affiliate_codes (
  code_id uuid primary key default gen_random_uuid(),
  affiliate_id uuid not null references public.affiliates(affiliate_id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

-- Clicks on referral links
create table if not exists public.affiliate_clicks (
  click_id uuid primary key default gen_random_uuid(),
  affiliate_id uuid not null references public.affiliates(affiliate_id) on delete cascade,
  code text,
  url text,
  ip inet,
  user_agent text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamptz not null default now()
);

-- Conversions / earnings generated by referrals
create table if not exists public.affiliate_earnings (
  earning_id uuid primary key default gen_random_uuid(),
  affiliate_id uuid not null references public.affiliates(affiliate_id) on delete cascade,
  code text,
  referred_user_id uuid,
  plan text,
  amount_cents integer not null default 0,
  currency text not null default 'UGX',
  status text not null default 'pending', -- pending|paid|rejected
  created_at timestamptz not null default now()
);

-- Minimal RLS setup (adjust as needed)
alter table public.affiliates enable row level security;
alter table public.affiliate_codes enable row level security;
alter table public.affiliate_clicks enable row level security;
alter table public.affiliate_earnings enable row level security;

-- Allow authenticated users to view their own affiliate rows
drop policy if exists affiliates_select_self on public.affiliates;
create policy affiliates_select_self on public.affiliates for select
  using (auth.uid() = user_id);
drop policy if exists affiliates_insert_self on public.affiliates;
create policy affiliates_insert_self on public.affiliates for insert
  with check (auth.uid() = user_id);

-- Codes visible via join; restrict inserts to owner/service role
drop policy if exists affiliate_codes_select_join on public.affiliate_codes;
create policy affiliate_codes_select_join on public.affiliate_codes for select
  using (exists(select 1 from public.affiliates a where a.affiliate_id = affiliate_codes.affiliate_id and a.user_id = auth.uid()));

-- Clicks/Earnings readable by affiliate owner
drop policy if exists affiliate_clicks_select_owner on public.affiliate_clicks;
create policy affiliate_clicks_select_owner on public.affiliate_clicks for select
  using (exists(select 1 from public.affiliates a where a.affiliate_id = affiliate_clicks.affiliate_id and a.user_id = auth.uid()));
drop policy if exists affiliate_earnings_select_owner on public.affiliate_earnings;
create policy affiliate_earnings_select_owner on public.affiliate_earnings for select
  using (exists(select 1 from public.affiliates a where a.affiliate_id = affiliate_earnings.affiliate_id and a.user_id = auth.uid()));

-- API routes should use service role for inserts to clicks/earnings


