package com.pwezacore.ui.navigation

sealed class Screen(val route: String) {
    object Login : Screen("login")
    object Register : Screen("register")
    object ForgotPassword : Screen("forgot_password")
    object Admin : Screen("admin")
    object AdminDashboard : Screen("admin/dashboard")
    object Students : Screen("admin/students")
    object Teachers : Screen("admin/teachers")
    object Parents : Screen("admin/parents")
    object Staff : Screen("admin/accounts")
    object Finance : Screen("admin/outstanding")
    object Reports : Screen("admin/reports/generate")
    object Attendance : Screen("admin/attendance-records")
    object ExamSets : Screen("admin/exam-sets")
    object Identity : Screen("admin/identity")
    object Classes : Screen("admin/settings/classes")
    object JobVacancies : Screen("admin/jobs")
    object SystemSettings : Screen("admin/settings")
    object Notifications : Screen("admin/notifications")
    object AddStudent : Screen("admin/students/add")
    object AddTeacher : Screen("admin/teachers/add")
    object AddParent : Screen("admin/parents/add")
    object RecordPayment : Screen("admin/record-payment")
    object SettingsSchoolProfile : Screen("admin/settings/school-profile")
    object SettingsSubjectsPerClass : Screen("admin/settings/subjects-per-class")
    object SettingsTeacherSubjectClass : Screen("admin/settings/teacher-subject-class")
    object SettingsTermSettings : Screen("admin/settings/term-settings")
    object SettingsTimetableDesigner : Screen("admin/settings/timetable-designer")
    object SettingsFinancial : Screen("admin/settings/financial")
    object SettingsSchoolRequirements : Screen("admin/settings/school-requirements")
    object SettingsLocation : Screen("admin/settings/location")
    object TeacherDashboard : Screen("teacher/dashboard")
    object StudentDashboard : Screen("student/dashboard")
    object ParentDashboard : Screen("parent/dashboard")
    object AccountantDashboard : Screen("accountant/dashboard")
    object LibrarianDashboard : Screen("librarian/dashboard")
    object HeadTeacherDashboard : Screen("head_teacher/dashboard")
    object OwnerDashboard : Screen("owner/dashboard")
}
