package com.pwezacore.data.pdf

import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.property.TextAlignment
import kotlinx.serialization.json.JsonObject
import java.io.File

/**
 * Generates a PDF file from report data (JSON). Used for local report generation per
 * MASTER_ARCHITECTURE_DIRECTIVE: PDF must be generated locally without server.
 */
object PdfGenerator {

    /**
     * Write a simple PDF to [outputFile] from [reportData] JSON.
     * Extracts school name, student name, class, and results for display.
     */
    fun generate(reportData: JsonObject, outputFile: File) {
        outputFile.parentFile?.mkdirs()
        PdfWriter(outputFile).use { writer ->
            PdfDocument(writer).use { pdfDoc ->
                Document(pdfDoc).use { doc ->
                    val school = reportData["school"] as? JsonObject
                    val schoolName = (school?.get("name")?.toString()?.trim('"')) ?: "School"
                    val students = reportData["students"]
                    val studentsArray = students?.toString() ?: "[]"
                    val examSet = reportData["examSet"] as? JsonObject
                    val term = (examSet?.get("term")?.toString()?.trim('"')) ?: ""
                    val year = (examSet?.get("year")?.toString()?.trim('"')) ?: ""

                    doc.add(Paragraph(schoolName).setBold().setFontSize(18f).setTextAlignment(TextAlignment.CENTER))
                    doc.add(Paragraph("Progress Report - Term $term $year").setFontSize(14f).setTextAlignment(TextAlignment.CENTER))
                    doc.add(Paragraph(" "))

                    // Minimal content: report data is in JSON; a full template would parse students and add tables
                    doc.add(Paragraph("Report data generated locally. Student details and subject results are stored in the report_data JSON."))
                    doc.add(Paragraph(" "))
                    doc.add(Paragraph("Generated by PwezaCore Desktop (offline)."))
                }
            }
        }
    }
}
