package com.pwezacore.data.repository

import com.pwezacore.data.local.entities.StudentEntity
import com.pwezacore.data.remote.SupabaseClient
import com.pwezacore.data.remote.dto.SchoolTermDto
import io.github.jan.supabase.postgrest.from
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import javax.inject.Inject
import javax.inject.Singleton

@Serializable
internal data class CurrentClassRow(@SerialName("current_class") val current_class: String? = null)

@Singleton
class ReportRepository @Inject constructor(
    private val supabaseClient: SupabaseClient,
    private val authRepository: AuthRepository
) {

    suspend fun getCurrentSchoolId(): String? = authRepository.getCurrentUser()?.school_id

    /** Load terms and distinct classes in parallel for speed. */
    suspend fun loadTermsAndClasses(schoolId: String): Pair<List<SchoolTermDto>, List<String>> = coroutineScope {
        val termsDeferred = async {
            try {
                supabaseClient.postgrest.from("school_terms")
                    .select { filter { eq("school_id", schoolId) } }
                    .decodeList<SchoolTermDto>()
                    .sortedWith(compareByDescending<SchoolTermDto> { it.year }.thenByDescending { it.term })
            } catch (e: Exception) {
                emptyList()
            }
        }
        val classesDeferred = async {
            try {
                val list = supabaseClient.postgrest.from("students")
                    .select(columns = io.github.jan.supabase.postgrest.query.Columns.list("current_class")) {
                        filter { eq("school_id", schoolId) }
                    }
                    .decodeList<CurrentClassRow>()
                list.mapNotNull { it.current_class }.distinct().sorted()
            } catch (e: Exception) {
                emptyList()
            }
        }
        termsDeferred.await() to classesDeferred.await()
    }

    suspend fun loadStudents(schoolId: String, className: String): List<StudentEntity> {
        return try {
            supabaseClient.postgrest.from("students")
                .select {
                    filter {
                        eq("school_id", schoolId)
                        eq("current_class", className)
                    }
                }
                .decodeList<StudentEntity>()
                .sortedBy { it.name }
        } catch (e: Exception) {
            emptyList()
        }
    }

    /** Build report summary from selected term, class and students. Fast, no extra network. */
    fun buildReportSummary(
        termLabel: String,
        className: String,
        students: List<StudentEntity>,
        singleStudent: StudentEntity?
    ): String {
        val sb = StringBuilder()
        sb.appendLine("STUDENT PROGRESS REPORT")
        sb.appendLine(termLabel)
        sb.appendLine("Class: $className")
        sb.appendLine()
        if (singleStudent != null) {
            sb.appendLine("Student: ${singleStudent.name}")
            sb.appendLine("Admission: ${singleStudent.admission_number ?: "—"}")
            sb.appendLine()
        } else {
            sb.appendLine("Students (${students.size}):")
            students.forEachIndexed { i, s -> sb.appendLine("  ${i + 1}. ${s.name} (${s.admission_number ?: "—"})") }
            sb.appendLine()
        }
        sb.appendLine("— Report generated by PwezaCore —")
        return sb.toString()
    }
}
